language: node_js
sudo: false
node_js:
  - "7"
  - "8"
  - "10"
# env:
#   matrix:
#     - 
# before_script:
#   - npm install
script: npm test
branches:
  only:
    - master
    - develop
